#include <stdio.h> 
#include <stdlib.h> 
#include <assert.h> 
#include <stdint.h> 
#include "allocator.h" 
#include "allocator.c" 
#define KNRM  "\x1B[0m"
#define KRED  "\x1B[31m"
#define KGRN  "\x1B[32m"
#define KYEL  "\x1B[33m"
#define KBLU  "\x1B[34m"
#define KMAG  "\x1B[35m"
#define KCYN  "\x1B[36m"
#define KWHT  "\x1B[37m"
void testInit(){
   fprintf(stderr, "%sInitializing vlad with size 1000...\n", KCYN);
   vlad_init(1000); 
   free_header_t *header = (free_header_t*) memory;
   if(memory == NULL) fprintf(stderr, "%sglobal memory var set to NULL!\n", KRED); 
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of 0!\n", KRED, free_list_ptr); 
   if(memory_size != 1024) fprintf(stderr, "%smemory_size global var = %d instead of 1024!\n", KRED, memory_size); 
   if(strategy != BEST_FIT) fprintf(stderr, "%sStrategy should be set to BEST_FIT (this test suite for BEST_FIT only).\n", KYEL); 
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 1024) fprintf(stderr, "%sheader->size is %d instead of 1024!\n", KRED, header->size); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of 0!\n", KRED, header->next); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of 0!\n", KRED, header->prev);  
   vlad_end(); 
   fprintf(stderr, "%sInitializing vlad with size 400...\n", KCYN);
   vlad_init(400);
   header = (free_header_t*) memory;
   if(memory == NULL) fprintf(stderr, "%sglobal memory var set to NULL!\n", KRED); 
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of 0!\n", KRED, free_list_ptr); 
   if(memory_size != 1024) fprintf(stderr, "%smemory_size global var = %d instead of 1024!\n", KRED, memory_size); 
   if(strategy != BEST_FIT) fprintf(stderr, "%sStrategy should be set to BEST_FIT (this test suite for BEST_FIT only).\n", KYEL); 
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 1024  ) fprintf(stderr, "%sheader->size is %d instead of 1024!\n", KRED, header->size); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of 0!\n", KRED, header->next); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of 0!\n", KRED, header->prev);  
   vlad_end();
   fprintf(stderr, "%sInitializing vlad with size 1042500...\n", KCYN);
   vlad_init(1042500);
   header = (free_header_t*) memory;
   if(memory == NULL) fprintf(stderr, "%sglobal memory var set to NULL!\n", KRED); 
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of 0!\n", KRED, free_list_ptr); 
   if(memory_size != 1048576) fprintf(stderr, "%smemory_size global var = %d instead of 1048576!\n", KRED, memory_size); 
   if(strategy != BEST_FIT) fprintf(stderr, "%sStrategy should be set to BEST_FIT (this test suite for BEST_FIT only).\n", KYEL); 
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 1048576) fprintf(stderr, "%sheader->size is %d instead of 1048576!\n", KRED, header->size); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of 0!\n", KRED, header->next); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of 0!\n", KRED, header->prev); 
   vlad_end(); 
   fprintf(stderr, "%sInitializing vlad with size 62000...\n", KCYN);
   vlad_init(62000);
   header = (free_header_t*) memory;
   if(memory == NULL) fprintf(stderr, "%sglobal memory var set to NULL!\n", KRED); 
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of 0!\n", KRED, free_list_ptr); 
   if(memory_size != 65536) fprintf(stderr, "%smemory_size global var = %d instead of 65536!\n", KRED, memory_size); 
   if(strategy != BEST_FIT) fprintf(stderr, "%sStrategy should be set to BEST_FIT (this test suite for BEST_FIT only).\n", KYEL); 
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 65536) fprintf(stderr, "%sheader->size is %d instead of 65536!\n", KRED, header->size); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of 0!\n", KRED, header->next); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of 0!\n", KRED, header->prev); 
   vlad_end(); 
   fprintf(stderr, "%sVlad_init tests completed. Errors in %sRed%s...\n", KGRN, KRED, KNRM);
   return;
}
void testMalloc(){
   fprintf(stderr, "%sInitializing vlad with size 1024...\n", KCYN);
   vlad_init(1024); 
   fprintf(stderr, "%sAttempting to allocate mlc1, region of size 52 (calling vlad_malloc(50))...\n", KCYN);
   byte *mlc1 = vlad_malloc(50);
   free_header_t *header = (free_header_t*) &memory[60];
   alloc_header_t *alloc = (alloc_header_t*) &memory[0];
   fprintf(stderr, "%sSetting header to memory[60], the first free block\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[0]\n", KMAG);
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 52 + ALLOC_HEADER_SIZE) fprintf(stderr, "%salloc->size is %d instead 60\n", KRED, alloc->size);
   if(free_list_ptr != 60) fprintf(stderr, "%sfree_list_ptr is %d instead of 60\n", KRED, free_list_ptr);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 1024-60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 1024-60); 
   if(header->next != 60) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 60); 
   if(header->prev != 60) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 60);  
   if(mlc1 != &memory[8]) fprintf(stderr, "%sThe address of mlc1 is %p instead of %p\n", KRED, mlc1, &memory[8]);
   fprintf(stderr, "%sfreeing mlc1...\n", KCYN);
   vlad_free(mlc1);
   fprintf(stderr, "%sSetting header to memory[0], the first free block\n", KMAG);
   header = (free_header_t*) &memory[0];
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of 0\n", KRED, free_list_ptr);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 1024) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 1024); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0); 
   fprintf(stderr, "%sAttempting to allocate mlc1, region of size %d (calling vlad_malloc(50))...\n", KCYN, 52);
   mlc1 = vlad_malloc(50);
   fprintf(stderr, "%sSetting header to memory[60], the first free block\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[0]\n", KMAG);
   header = (free_header_t*) &memory[60];
   alloc = (alloc_header_t*) &memory[0];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 60) fprintf(stderr, "%salloc->size is %d instead 60\n", KRED, alloc->size);
   if(free_list_ptr != 60) fprintf(stderr, "%sfree_list_ptr is %d instead of 60\n", KRED, free_list_ptr);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 1024-60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 1024-60); 
   if(header->next != 60) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 60); 
   if(header->prev != 60) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 60);  
   if(mlc1 != &memory[8]) fprintf(stderr, "%sThe address of mlc1 is %p instead of %p\n", KRED, mlc1, &memory[8]);
   fprintf(stderr, "%sAttempting to allocate mlc2, region of size %d (calling vlad_malloc(100))...\n", KCYN, 100);
   byte *mlc2 = vlad_malloc(100);
   header = (free_header_t*) &memory[60 + 100 + ALLOC_HEADER_SIZE];
   alloc = (alloc_header_t*) &memory[60];
   fprintf(stderr, "%sSetting header to memory[168], the first free block\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[60]\n", KMAG);
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 108) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 108);
   if(free_list_ptr != 168) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 168);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 1024-60-108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 1024-60-108); 
   if(header->next != 168) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 168); 
   if(header->prev != 168) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 168);  
   if(mlc2 != &memory[68]) fprintf(stderr, "%sThe address of mlc2 is %p instead of %p\n", KRED, mlc2, &memory[68]);
   fprintf(stderr, "%sAttempting to allocate mlc3, region of size %d (calling vlad_malloc(100))...\n", KCYN, 100);
   byte *mlc3 = vlad_malloc(100);
   fprintf(stderr, "%sSetting header to memory[276], the first free block\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[168]\n", KMAG);
   header = (free_header_t*) &memory[276];
   alloc = (alloc_header_t*) &memory[168];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 108) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 108);
   if(free_list_ptr != 276) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 276);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 748) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 748); 
   if(header->next != 276) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 276); 
   if(header->prev != 276) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 276);  
   if(mlc3 != &memory[176]) fprintf(stderr, "%sThe address of mlc3 is %p instead of %p\n", KRED, mlc3, &memory[176]);
   fprintf(stderr, "%sfreeing mlc2...\n", KCYN);
   vlad_free(mlc2);
   fprintf(stderr, "%sSetting header to memory[60], the first free block\n", KMAG);
   header = (free_header_t*) &memory[60];
   if(free_list_ptr != 60) fprintf(stderr, "%sfree_list_ptr = %d instead of %d\n", KRED, free_list_ptr, 60);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 108); 
   if(header->next != 276) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 276); 
   if(header->prev != 276) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 276); 
   fprintf(stderr, "%sSetting header to memory[276], the second free block\n", KMAG);
   header = (free_header_t*) &memory[276];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 748) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 748); 
   if(header->next != 60) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 60); 
   if(header->prev != 60) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 60); 
   header = (free_header_t*) &memory[276];
   fprintf(stderr, "%sAttempting to allocate mlc4, region of size %d (calling vlad_malloc(108))...\n", KCYN, 108);
   byte *mlc4 = vlad_malloc(108);
   fprintf(stderr, "%sSetting header to memory[392], the second free block\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[276]\n", KMAG);
   header = (free_header_t*) &memory[392];
   alloc = (alloc_header_t*) &memory[276];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 116) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 116);
   if(free_list_ptr != 60) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 60);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 632) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 632); 
   if(header->next != 60) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 60); 
   if(header->prev != 60) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 60);  
   if(mlc4 != &memory[284]) fprintf(stderr, "%sThe address of mlc4 is %p instead of %p\n", KRED, mlc4, &memory[284]);
   fprintf(stderr, "%sAttempting to allocate mlc2, region of size %d (calling vlad_malloc(80))...\n", KCYN, 80);
   mlc2 = vlad_malloc(80);
   fprintf(stderr, "%sSetting header to memory[392], the first free block (note that 108 < threshold)\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[60]\n", KMAG);
   header = (free_header_t*) &memory[392];
   alloc = (alloc_header_t*) &memory[60];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 108) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 108);
   if(free_list_ptr != 392) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 392);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 632) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 632); 
   if(header->next != 392) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 392); 
   if(header->prev != 392) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 392);  
   if(mlc2 != &memory[68]) fprintf(stderr, "%sThe address of mlc2 is %p instead of %p\n", KRED, mlc2, &memory[68]);
   fprintf(stderr, "%sAttempting to allocate mlc5, region of size %d (calling vlad_malloc(100))...\n", KCYN, 100);
   byte *mlc5 = vlad_malloc(100);
   fprintf(stderr, "%sSetting header to memory[500], the first free block\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[392]\n", KMAG);
   header = (free_header_t*) &memory[500];
   alloc = (alloc_header_t*) &memory[392];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 108) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 108);
   if(free_list_ptr != 500) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 500);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 524) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 524); 
   if(header->next != 500) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 500); 
   if(header->prev != 500) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 500);  
   if(mlc5 != &memory[400]) fprintf(stderr, "%sThe address of mlc5 is %p instead of %p\n", KRED, mlc5, &memory[400]);
   fprintf(stderr, "%sAttempting to allocate mlc6, region of size %d (calling vlad_malloc(100))...\n", KCYN, 100);
   byte *mlc6 = vlad_malloc(100);
   fprintf(stderr, "%sSetting header to memory[608], the first free block\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[500]\n", KMAG);
   header = (free_header_t*) &memory[608];
   alloc = (alloc_header_t*) &memory[500];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 108) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 108);
   if(free_list_ptr != 608) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 608);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 416) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 416); 
   if(header->next != 608) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 608); 
   if(header->prev != 608) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 608);  
   if(mlc6 != &memory[508]) fprintf(stderr, "%sThe address of mlc6 is %p instead of %p\n", KRED, mlc6, &memory[508]);
   fprintf(stderr, "%sfreeing mlc1...\n", KCYN);
   vlad_free(mlc1);
   fprintf(stderr, "%sSetting header to memory[0], the first free block\n", KMAG);
   header = (free_header_t*) &memory[0];
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of %d\n", KRED, free_list_ptr, 0);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 60); 
   if(header->next != 608) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 608); 
   if(header->prev != 608) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 608); 
   fprintf(stderr, "%sSetting header to memory[608], the second free block\n", KMAG);
   header = (free_header_t*) &memory[608];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 416) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 416); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0); 
   fprintf(stderr, "%sfreeing mlc3...\n", KCYN);
   vlad_free(mlc3);
   fprintf(stderr, "%sSetting header to memory[0], the first free block\n", KMAG);
   header = (free_header_t*) &memory[0];
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of %d\n", KRED, free_list_ptr, 0);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 60); 
   if(header->next != 168) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 168); 
   if(header->prev != 608) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 608); 
   fprintf(stderr, "%sSetting header to memory[168], the second free block\n", KMAG);
   header = (free_header_t*) &memory[168];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 108); 
   if(header->next != 608) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 608); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0);
   fprintf(stderr, "%sSetting header to memory[608], the third free block\n", KMAG);
   header = (free_header_t*) &memory[608];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 416) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 416); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 168) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 168);
   fprintf(stderr, "%sfreeing mlc5...\n", KCYN);
   vlad_free(mlc5);
   fprintf(stderr, "%sSetting header to memory[0], the first free block\n", KMAG);
   header = (free_header_t*) &memory[0];
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of %d\n", KRED, free_list_ptr, 0);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 60); 
   if(header->next != 168) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 168); 
   if(header->prev != 608) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 608); 
   fprintf(stderr, "%sSetting header to memory[168], the second free block\n", KMAG);
   header = (free_header_t*) &memory[168];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 108); 
   if(header->next != 392) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 392); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0);
   fprintf(stderr, "%sSetting header to memory[392], the third free block\n", KMAG);
   header = (free_header_t*) &memory[392];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 108); 
   if(header->next != 608) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 608); 
   if(header->prev != 168) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 168);
   fprintf(stderr, "%sSetting header to memory[608], the fourth free block\n", KMAG);
   header = (free_header_t*) &memory[608];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 416) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 416); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 392) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 392);
   fprintf(stderr, "%sAttempting to allocate mlc7, region of size %d (calling vlad_malloc(1000))...\n", KCYN, 1000);
   byte *mlc7 = vlad_malloc(1000);
   if (mlc7 != NULL) fprintf(stderr, "%saddress mlc7 is %p instead of NULL!\n", KRED, mlc7);
   fprintf(stderr, "%sAttempting to allocate mlc7, region of size %d (calling vlad_malloc(408))...\n", KCYN, 408);
   mlc7 = vlad_malloc(408);
   fprintf(stderr, "%sSetting header to memory[0], the first free block\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[608]\n", KMAG);
   header = (free_header_t*) &memory[0];
   alloc = (alloc_header_t*) &memory[608];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 416) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 416);
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 0);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 60); 
   if(header->next != 168) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 168); 
   if(header->prev != 392) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 392);  
   if(mlc7 != &memory[616]) fprintf(stderr, "%sThe address of mlc7 is %p instead of %p\n", KRED, mlc7, &memory[616]);
   fprintf(stderr, "%sSetting header to memory[168], the second free block\n", KMAG);
   header = (free_header_t*) &memory[168];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 108); 
   if(header->next != 392) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 392); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0);
   fprintf(stderr, "%sSetting header to memory[392], the third free block\n", KMAG);
   header = (free_header_t*) &memory[392];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 108); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 168) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 168);
   fprintf(stderr, "%sAttempting to allocate mlc3, region of size %d (calling vlad_malloc(80))...\n", KCYN, 80);
   mlc3 = vlad_malloc(80);
   fprintf(stderr, "%sSetting header to memory[0], the first free block (note that 108 < threshold)\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[168]\n", KMAG);
   header = (free_header_t*) &memory[0];
   alloc = (alloc_header_t*) &memory[168];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 108) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 108);
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 0);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 60); 
   if(header->next != 392) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 392); 
   if(header->prev != 392) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 392);  
   if(mlc3 != &memory[176]) fprintf(stderr, "%sThe address of mlc3 is %p instead of %p\n", KRED, mlc3, &memory[176]);
   fprintf(stderr, "%sSetting header to memory[392], the second free block\n", KMAG);
   header = (free_header_t*) &memory[392];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 108); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0);
   fprintf(stderr, "%sAttempting to allocate mlc5, region of size %d (calling vlad_malloc(82))...\n", KCYN, 82);
   mlc5 = vlad_malloc(82);
   fprintf(stderr, "%sSetting header to memory[0], the first free block (note that 108 < threshold)\n", KMAG);
   fprintf(stderr, "%sSetting alloc to memory[392]\n", KMAG);
   header = (free_header_t*) &memory[0];
   alloc = (alloc_header_t*) &memory[392];
   if(alloc->magic != MAGIC_ALLOC) fprintf(stderr, "%salloc->magic is %d instead of %d\n", KRED, alloc->magic, MAGIC_ALLOC);
   if(alloc->size != 108) fprintf(stderr, "%salloc->size is %d instead %d\n", KRED, alloc->size, 108);
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr is %d instead of %d\n", KRED, free_list_ptr, 0);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 60); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0);  
   if(mlc5 != &memory[400]) fprintf(stderr, "%sThe address of mlc5 is %p instead of %p\n", KRED, mlc5, &memory[400]);
   fprintf(stderr, "%sAttempting to allocate mlc1, region of size %d (calling vlad_malloc(50))...\n", KCYN, 50);
   mlc1 = vlad_malloc(50);
   if (mlc1 != NULL) fprintf(stderr, "%saddress mlc1 is %p instead of NULL! (note that 60 < threshold and allocating mlc1 would leave 0 free regions\n", KRED, mlc1);
   fprintf(stderr, "%sAttempting to allocate mlc1, region of size %d (calling vlad_malloc(24))...\n", KCYN, 24);
   mlc1 = vlad_malloc(24);
   if (mlc1 != NULL) fprintf(stderr, "%saddress mlc1 is %p instead of NULL! (note that 60 < threshold and allocating mlc1 would leave 0 free regions\n", KRED, mlc1);
   fprintf(stderr, "%sfreeing mlc3...\n", KCYN);
   vlad_free(mlc3);
   fprintf(stderr, "%sSetting header to memory[0], the first free block\n", KMAG);
   header = (free_header_t*) &memory[0];
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of %d\n", KRED, free_list_ptr, 0);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 60) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 60); 
   if(header->next != 168) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 168); 
   if(header->prev != 168) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 168); 
   fprintf(stderr, "%sSetting header to memory[168], the second free block\n", KMAG);
   header = (free_header_t*) &memory[168];
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader->magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 108) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 108); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0);
   fprintf(stderr, "%sfreeing mlc2...\n", KCYN);
   vlad_free(mlc2);
   fprintf(stderr, "%sSetting header to memory[0], the first free block\n", KMAG);
   header = (free_header_t*) &memory[0];
   if(free_list_ptr != 0) fprintf(stderr, "%sfree_list_ptr = %d instead of %d\n", KRED, free_list_ptr, 0);
   if(header->magic != MAGIC_FREE) fprintf(stderr, "%sheader-magic is %d instead of %d\n", KRED, header->magic, MAGIC_FREE); 
   if(header->size != 276) fprintf(stderr, "%sheader->size is %d instead of %d!\n", KRED, header->size, 276); 
   if(header->next != 0) fprintf(stderr, "%sheader->next is %u instead of %d!\n", KRED, header->next, 0); 
   if(header->prev != 0) fprintf(stderr, "%sheader->prev is %u instead of %d!\n", KRED, header->prev, 0); 
}
int main (int argc, char * argv[]){
   fprintf(stderr, "%sTesting vlad_init...\n", KNRM);
   testInit();
   fprintf(stderr, "%sTesting vlad_malloc and vlad_free and vlad_merge...\n", KNRM);
   testMalloc();
   fprintf(stderr, "%sAll tests compeleted, errors highlighted in %sred%s...\n", KGRN, KRED, KNRM);
   return EXIT_SUCCESS;
}
